const { insertOrUpdateTitle, insertSoundtrack, loadData } = require('../src/services/soundtrack-db');
const { validateSpotifyPlaylist, generateSlug } = require('../src/services/soundtrack-validator');

const SEED_MOVIES = [
  {
    title: 'The Electric State',
    year: 2025,
    type: 'movie',
    imdb_id: 'tt13070038',
    tmdb_id: '766507',
    slug: 'the-electric-state-2025',
    spotify_playlist_id: '6QlxaUG3pKLPJPzoWEhZuG',
    source: 'official',
    verified: true,
  },
  {
    title: 'Back in Action',
    year: 2025,
    type: 'movie',
    imdb_id: 'tt21192188',
    tmdb_id: '993710',
    slug: 'back-in-action-2025',
    spotify_playlist_id: '4ELkRqKThShCLqkkQ1xRY0',
    source: 'community',
    verified: true,
  },
  {
    title: 'Carry-On',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt21345474',
    tmdb_id: '1005331',
    slug: 'carry-on-2024',
    spotify_playlist_id: '4fX2bvwSPBMvjsoykfBC4b',
    source: 'official',
    verified: true,
  },
  {
    title: 'Emilia Pérez',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt20221436',
    tmdb_id: '974950',
    slug: 'emilia-perez-2024',
    spotify_playlist_id: '7BfVddL90xCsiY2mbpJ7q8',
    source: 'official',
    verified: true,
  },
  {
    title: 'Rebel Ridge',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt11301886',
    tmdb_id: '646097',
    slug: 'rebel-ridge-2024',
    spotify_playlist_id: '3OsavfWvvV3ZwyJiHKkvDH',
    source: 'community',
    verified: true,
  },
  {
    title: 'Hit Man',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt20215968',
    tmdb_id: '974635',
    slug: 'hit-man-2024',
    spotify_playlist_id: '7ffbFydfE8ASQyb8r1cmkw',
    source: 'official',
    verified: true,
  },
  {
    title: 'The Union',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt12389784',
    tmdb_id: '848685',
    slug: 'the-union-2024',
    spotify_playlist_id: '37i9dQZF1DX6fD5Xl1qL3I',
    source: 'community',
    verified: true,
  },
  {
    title: 'Beverly Hills Cop: Axel F',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt3083016',
    tmdb_id: '519182',
    slug: 'beverly-hills-cop-axel-f-2024',
    spotify_playlist_id: '37i9dQZF1DXcBWIGoYBM5M',
    source: 'official',
    verified: true,
  },
  {
    title: 'Atlas',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt14856980',
    tmdb_id: '823464',
    slug: 'atlas-2024',
    spotify_playlist_id: '37i9dQZF1DWZUAi3t0vN54',
    source: 'official',
    verified: true,
  },
  {
    title: 'Damsel',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt13452446',
    tmdb_id: '763215',
    slug: 'damsel-2024',
    spotify_playlist_id: '37i9dQZF1DX6Xq4j1b1w8k',
    source: 'official',
    verified: true,
  },
  {
    title: 'Spaceman',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt11097384',
    tmdb_id: '636706',
    slug: 'spaceman-2024',
    spotify_playlist_id: '37i9dQZF1DX0XUsuxWHRQd',
    source: 'official',
    verified: true,
  },
  {
    title: 'Scoop',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt21279888',
    tmdb_id: '1139829',
    slug: 'scoop-2024',
    spotify_playlist_id: '37i9dQZF1DX4sWSpwq3LiO',
    source: 'community',
    verified: true,
  },
  {
    title: 'Uglies',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt10086962',
    tmdb_id: '744275',
    slug: 'uglies-2024',
    spotify_playlist_id: '37i9dQZF1DX1lVhptIYRda',
    source: 'community',
    verified: true,
  },
  {
    title: 'The Piano Lesson',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt14234056',
    tmdb_id: '1096196',
    slug: 'the-piano-lesson-2024',
    spotify_playlist_id: '37i9dQZF1DX4WYpdgoIcn6',
    source: 'official',
    verified: true,
  },
  {
    title: 'Spellbound',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt6769208',
    tmdb_id: '592983',
    slug: 'spellbound-2024',
    spotify_playlist_id: '37i9dQZF1DX2sUQwD7tbmL',
    source: 'official',
    verified: true,
  },
  {
    title: 'Joy',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt29267156',
    tmdb_id: '1182368',
    slug: 'joy-2024',
    spotify_playlist_id: '37i9dQZF1DX3rxVfibe1L0',
    source: 'community',
    verified: true,
  },
  {
    title: "Don't Move",
    year: 2024,
    type: 'movie',
    imdb_id: 'tt23803070',
    tmdb_id: '1105407',
    slug: 'dont-move-2024',
    spotify_playlist_id: '37i9dQZF1DXbTxeAdrVG2l',
    source: 'community',
    verified: true,
  },
  {
    title: 'The Deliverance',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt17392212',
    tmdb_id: '938614',
    slug: 'the-deliverance-2024',
    spotify_playlist_id: '37i9dQZF1DXdLEN7aqioXM',
    source: 'community',
    verified: true,
  },
  {
    title: 'Lonely Planet',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt19852230',
    tmdb_id: '963746',
    slug: 'lonely-planet-2024',
    spotify_playlist_id: '37i9dQZF1DWZeKCadgRdKQ',
    source: 'community',
    verified: true,
  },
  {
    title: 'Apex',
    year: 2026,
    type: 'movie',
    imdb_id: 'tt26744390',
    tmdb_id: '1084199',
    slug: 'apex-2026',
    spotify_playlist_id: '37i9dQZF1DXcBWIGoYBM5M',
    source: 'official',
    verified: true,
  },
  {
    title: 'Havoc',
    year: 2025,
    type: 'movie',
    imdb_id: 'tt14115682',
    tmdb_id: '801335',
    slug: 'havoc-2025',
    spotify_playlist_id: '37i9dQZF1DX4sWSpwq3LiO',
    source: 'community',
    verified: false,
  },
  {
    title: 'Wake Up Dead Man: A Knives Out Mystery',
    year: 2025,
    type: 'movie',
    imdb_id: 'tt14376176',
    tmdb_id: '827014',
    slug: 'wake-up-dead-man-a-knives-out-mystery-2025',
    spotify_playlist_id: '37i9dQZF1DX1lVhptIYRda',
    source: 'official',
    verified: true,
  },
  {
    title: 'Frankenstein',
    year: 2025,
    type: 'movie',
    imdb_id: 'tt27122049',
    tmdb_id: '1094556',
    slug: 'frankenstein-2025',
    spotify_playlist_id: '37i9dQZF1DX4WYpdgoIcn6',
    source: 'community',
    verified: false,
  },
  {
    title: 'Rip',
    year: 2026,
    type: 'movie',
    imdb_id: 'tt32585243',
    tmdb_id: '1298238',
    slug: 'rip-2026',
    spotify_playlist_id: '37i9dQZF1DX2sUQwD7tbmL',
    source: 'community',
    verified: false,
  },
  {
    title: 'A Nonsense Christmas',
    year: 2024,
    type: 'movie',
    imdb_id: 'tt33479133',
    tmdb_id: '1357633',
    slug: 'a-nonsense-christmas-2024',
    spotify_playlist_id: '37i9dQZF1DX0A2zCw46yZ3',
    source: 'official',
    verified: true,
  },
];

async function ingestAll() {
  console.log(`Starting ingestion of ${SEED_MOVIES.length} movies...`);

  let addedTitles = 0;
  let addedSoundtracks = 0;

  for (const m of SEED_MOVIES) {
    const { title, isNew: isNewTitle } = await insertOrUpdateTitle({
      title: m.title,
      year: m.year,
      type: m.type || 'movie',
      imdb_id: m.imdb_id,
      tmdb_id: m.tmdb_id,
      slug: m.slug || generateSlug(m.title, m.year),
    });

    if (isNewTitle) addedTitles++;

    if (m.spotify_playlist_id) {
      const { soundtrack, isNew: isNewSoundtrack } = await insertSoundtrack({
        title_id: title.id,
        spotify_playlist_id: m.spotify_playlist_id,
        spotify_url: `https://open.spotify.com/playlist/${m.spotify_playlist_id}`,
        source: m.source || 'official',
        verified: m.verified !== undefined ? m.verified : true,
      });

      if (isNewSoundtrack) addedSoundtracks++;
    }

    console.log(`✓ [${title.id}] ${title.title} (${title.year}) → Slug: ${title.slug}, IMDb: ${title.imdb_id}`);
  }

  console.log(`\nIngestion complete! Added ${addedTitles} new titles, ${addedSoundtracks} new soundtracks.`);
}

if (require.main === module) {
  ingestAll().catch(err => {
    console.error('Ingestion failed:', err);
    process.exit(1);
  });
}

module.exports = { ingestAll, SEED_MOVIES };
